#!/usr/bin/env python3

from digikey import Session

d = Session(country='CA')
d.init_groups()

cat = d.categories['Integrated Circuits (ICs)/Memory']
cat.init_params()
resp = cat.search({cat.params['In Stock']: 1,
                   cat.params['Technology']: {'DRAM - EDO'}})

pass
